// Auto-generated by scripts/config_key_sync.py — DO NOT EDIT
// Source: config/stylus_pipeline_config.yaml

#include "StylusPipelineConfigKeys.h"
#include "SolverBuildConfig.h"

#if EGOTOUCH_CONFIG_ENABLED

#include "StylusPipeline.h"
#include "ConfigParse.h"

#include <algorithm>
#include <ostream>

namespace Solvers {
namespace StylusConfig {

// ── GetConfigSchema ──
std::vector<ConfigParam> GetConfigSchema(StylusPipelineMembers& m) {
    std::vector<ConfigParam> s;
    s.reserve(41);

    // ── Frame Parser ──
    s.emplace_back(kSpFrameParserEnabledName, "Frame Parser Enabled", ConfigParam::Bool, const_cast<bool*>(&m.frameParser->m_enabled)).Module("Frame Parser");

    // ── Data Solve ──
    s.emplace_back(kSpPeakDetectorEnabledName, "Peak Detector Enabled", ConfigParam::Bool, const_cast<bool*>(&m.featureExtractor->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpCoordinateSolverEnabledName, "Coordinate Solver Enabled", ConfigParam::Bool, const_cast<bool*>(&m.coordinateSolver->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpTiltProcessEnabledName, "Tilt Process Enabled", ConfigParam::Bool, const_cast<bool*>(&m.tiltProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpPressureSolverEnabledName, "Pressure Solver Enabled", ConfigParam::Bool, const_cast<bool*>(&m.pressureSolver->m_enabled)).Module("Data Solve");

    // ── Pressure ──
    s.emplace_back(kSpPostPressureEnabledName, "Post Pressure Enabled", ConfigParam::Bool, const_cast<bool*>(&m.postPressure->m_enabled)).Module("Pressure");
    s.emplace_back(kSpFakePressureDecreaseEnabledName, "Fake Pressure Decrease Enabled", ConfigParam::Bool, const_cast<bool*>(&m.postPressure->m_fakePressureDecreaseEnabled)).Module("Pressure");
    s.emplace_back(kSpBtFreqShiftDebounceFramesName, "BT Freq Shift Debounce Frames", ConfigParam::Int, const_cast<int*>(&m.postPressure->m_btFreqShiftDebounceFrames), 0, 255).Module("Pressure");
    s.emplace_back(kSpPressureEdgeEnterThresholdName, "Pressure Edge Enter Threshold", ConfigParam::UInt16, const_cast<uint16_t*>(&m.postPressure->m_pressureEdgeEnterThreshold), 0, 65535).Module("Pressure");
    s.emplace_back(kSpPressureEdgeExitThresholdName, "Pressure Edge Exit Threshold", ConfigParam::UInt16, const_cast<uint16_t*>(&m.postPressure->m_pressureEdgeExitThreshold), 0, 65535).Module("Pressure");
    s.emplace_back(kSpTipDownPressureThresholdName, "Tip Down Pressure Threshold", ConfigParam::UInt16, const_cast<uint16_t*>(&m.pressureSolver->m_tipDownPressureThreshold), 0, 4095).Module("Pressure");
    s.emplace_back(kSpBtPressSignalSuppressEnterThresholdName, "BT Press Suppress Enter Threshold", ConfigParam::UInt16, const_cast<uint16_t*>(&m.pressureSolver->m_btPressSignalSuppressEnterThreshold), 0, 65535).Module("Pressure");
    s.emplace_back(kSpBtPressSignalSuppressExitThresholdName, "BT Press Suppress Exit Threshold", ConfigParam::UInt16, const_cast<uint16_t*>(&m.pressureSolver->m_btPressSignalSuppressExitThreshold), 0, 65535).Module("Pressure");

    // ── Coordinate ──
    s.emplace_back(kSpSignalFloorName, "Signal Floor", ConfigParam::UInt16, const_cast<uint16_t*>(&m.coordinateSolver->m_signalFloor), 0, 65535).Module("Coordinate");

    // ── Data Solve ──
    s.emplace_back(kSpEdgeCoorEnabledName, "Edge Coor Process Enabled", ConfigParam::Bool, const_cast<bool*>(&m.edgeCoorProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpEdgeCoorPostEnabledName, "Edge Coor Post Process Enabled", ConfigParam::Bool, const_cast<bool*>(&m.edgeCoorPostProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpNoisePostEnabledName, "Noise Post Process Enabled", ConfigParam::Bool, const_cast<bool*>(&m.noisePostProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpNoiseSignalRatioTholdName, "Noise Signal Ratio Threshold", ConfigParam::UInt8, const_cast<uint8_t*>(&m.noisePostProcess->m_signalRatioThreshold), 1, 16).Module("Data Solve");
    s.emplace_back(kSpNoiseSignalDropRatioName, "Noise Signal Magnitude Drop Ratio", ConfigParam::UInt8, const_cast<uint8_t*>(&m.noisePostProcess->m_signalMagnitudeDropRatio), 1, 16).Module("Data Solve");
    s.emplace_back(kSpLinearFilterEnabledName, "Linear Filter Enabled", ConfigParam::Bool, const_cast<bool*>(&m.linearFilterProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpCoorReviseEnabledName, "CoorRevise Enabled", ConfigParam::Bool, const_cast<bool*>(&m.coorReviseProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpCoorReviseFactorDim1Name, "CoorRevise Factor Dim1", ConfigParam::Int, const_cast<int*>(&m.coorReviseProcess->m_factorDim1), 0, 255).Module("Data Solve");
    s.emplace_back(kSpCoorReviseFactorDim2Name, "CoorRevise Factor Dim2", ConfigParam::Int, const_cast<int*>(&m.coorReviseProcess->m_factorDim2), 0, 255).Module("Data Solve");
    s.emplace_back(kSpCoorSpeedEnabledName, "Coor Speed Enabled", ConfigParam::Bool, const_cast<bool*>(&m.coorSpeedProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpIirFilterEnabledName, "IIR Filter Enabled", ConfigParam::Bool, const_cast<bool*>(&m.coorIIRProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpIirCoefLowInBandName, "IIR Coef Low In-Band", ConfigParam::UInt8, const_cast<uint8_t*>(&m.coorIIRProcess->m_coefLowInBand), 0, 255).Module("Data Solve");
    s.emplace_back(kSpIirCoefHighInBandName, "IIR Coef High In-Band", ConfigParam::UInt8, const_cast<uint8_t*>(&m.coorIIRProcess->m_coefHighInBand), 0, 255).Module("Data Solve");
    s.emplace_back(kSpIirSpeedTholdInBandName, "IIR Speed Thold In-Band", ConfigParam::UInt8, const_cast<uint8_t*>(&m.coorIIRProcess->m_speedTholdInBand), 0, 255).Module("Data Solve");
    s.emplace_back(kSpIirCoefLowEdgeName, "IIR Coef Low Edge", ConfigParam::UInt8, const_cast<uint8_t*>(&m.coorIIRProcess->m_coefLowEdge), 0, 255).Module("Data Solve");
    s.emplace_back(kSpIirCoefHighEdgeName, "IIR Coef High Edge", ConfigParam::UInt8, const_cast<uint8_t*>(&m.coorIIRProcess->m_coefHighEdge), 0, 255).Module("Data Solve");
    s.emplace_back(kSpIirSpeedTholdEdgeName, "IIR Speed Thold Edge", ConfigParam::UInt8, const_cast<uint8_t*>(&m.coorIIRProcess->m_speedTholdEdge), 0, 255).Module("Data Solve");
    s.emplace_back(kSpIirSpeedMaxName, "IIR Speed Max", ConfigParam::Int, const_cast<int*>(&m.coorIIRProcess->m_speedMax), 0, 1000).Module("Data Solve");
    s.emplace_back(kSpIirMaxCoefName, "IIR Max Coef (Denominator)", ConfigParam::UInt8, const_cast<uint8_t*>(&m.coorIIRProcess->m_maxCoef), 0, 255).Module("Data Solve");
    s.emplace_back(kSpAftCoorEnabledName, "AFT Coor Process Enabled", ConfigParam::Bool, const_cast<bool*>(&m.aftCoorProcess->m_enabled)).Module("Data Solve");
    s.emplace_back(kSpLockFlashInBandXName, "Lock Flash In-Band X", ConfigParam::UInt8, const_cast<uint8_t*>(&m.aftCoorProcess->m_lockFlashInBandX), 0, 255).Module("Data Solve");
    s.emplace_back(kSpLockFlashInBandYName, "Lock Flash In-Band Y", ConfigParam::UInt8, const_cast<uint8_t*>(&m.aftCoorProcess->m_lockFlashInBandY), 0, 255).Module("Data Solve");
    s.emplace_back(kSpLockFlashEdgeXName, "Lock Flash Edge X", ConfigParam::UInt8, const_cast<uint8_t*>(&m.aftCoorProcess->m_lockFlashEdgeX), 0, 255).Module("Data Solve");
    s.emplace_back(kSpLockFlashEdgeYName, "Lock Flash Edge Y", ConfigParam::UInt8, const_cast<uint8_t*>(&m.aftCoorProcess->m_lockFlashEdgeY), 0, 255).Module("Data Solve");
    s.emplace_back(kSpLockSensorTxCountName, "Lock Sensor TX Count", ConfigParam::Int, const_cast<int*>(&m.aftCoorProcess->m_sensorTxCount), 1, 200).Module("Data Solve");
    s.emplace_back(kSpLockSensorRxCountName, "Lock Sensor RX Count", ConfigParam::Int, const_cast<int*>(&m.aftCoorProcess->m_sensorRxCount), 1, 200).Module("Data Solve");
    s.emplace_back(kSpLockBypassName, "Lock Bypass", ConfigParam::Bool, const_cast<bool*>(&m.aftCoorProcess->m_bypassLock)).Module("Data Solve");

    return s;
}

// ── SaveConfig ──
void SaveConfig(const StylusPipelineMembers& m, std::ostream& out) {
    out << kSpFrameParserEnabledName << "=" << (m.frameParser->m_enabled ? "1" : "0") << "\n";
    out << kSpPeakDetectorEnabledName << "=" << (m.featureExtractor->m_enabled ? "1" : "0") << "\n";
    out << kSpCoordinateSolverEnabledName << "=" << (m.coordinateSolver->m_enabled ? "1" : "0") << "\n";
    out << kSpTiltProcessEnabledName << "=" << (m.tiltProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpPressureSolverEnabledName << "=" << (m.pressureSolver->m_enabled ? "1" : "0") << "\n";
    out << kSpPostPressureEnabledName << "=" << (m.postPressure->m_enabled ? "1" : "0") << "\n";
    out << kSpFakePressureDecreaseEnabledName << "=" << (m.postPressure->m_fakePressureDecreaseEnabled ? "1" : "0") << "\n";
    out << kSpBtFreqShiftDebounceFramesName << "=" << m.postPressure->m_btFreqShiftDebounceFrames << "\n";
    out << kSpPressureEdgeEnterThresholdName << "=" << m.postPressure->m_pressureEdgeEnterThreshold << "\n";
    out << kSpPressureEdgeExitThresholdName << "=" << m.postPressure->m_pressureEdgeExitThreshold << "\n";
    out << kSpTipDownPressureThresholdName << "=" << m.pressureSolver->m_tipDownPressureThreshold << "\n";
    out << kSpBtPressSignalSuppressEnterThresholdName << "=" << m.pressureSolver->m_btPressSignalSuppressEnterThreshold << "\n";
    out << kSpBtPressSignalSuppressExitThresholdName << "=" << m.pressureSolver->m_btPressSignalSuppressExitThreshold << "\n";
    out << kSpSignalFloorName << "=" << m.coordinateSolver->m_signalFloor << "\n";
    out << kSpEdgeCoorEnabledName << "=" << (m.edgeCoorProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpEdgeCoorPostEnabledName << "=" << (m.edgeCoorPostProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpNoisePostEnabledName << "=" << (m.noisePostProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpNoiseSignalRatioTholdName << "=" << static_cast<int>(m.noisePostProcess->m_signalRatioThreshold) << "\n";
    out << kSpNoiseSignalDropRatioName << "=" << static_cast<int>(m.noisePostProcess->m_signalMagnitudeDropRatio) << "\n";
    out << kSpLinearFilterEnabledName << "=" << (m.linearFilterProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpCoorReviseEnabledName << "=" << (m.coorReviseProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpCoorReviseFactorDim1Name << "=" << m.coorReviseProcess->m_factorDim1 << "\n";
    out << kSpCoorReviseFactorDim2Name << "=" << m.coorReviseProcess->m_factorDim2 << "\n";
    out << kSpCoorSpeedEnabledName << "=" << (m.coorSpeedProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpIirFilterEnabledName << "=" << (m.coorIIRProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpIirCoefLowInBandName << "=" << static_cast<int>(m.coorIIRProcess->m_coefLowInBand) << "\n";
    out << kSpIirCoefHighInBandName << "=" << static_cast<int>(m.coorIIRProcess->m_coefHighInBand) << "\n";
    out << kSpIirSpeedTholdInBandName << "=" << static_cast<int>(m.coorIIRProcess->m_speedTholdInBand) << "\n";
    out << kSpIirCoefLowEdgeName << "=" << static_cast<int>(m.coorIIRProcess->m_coefLowEdge) << "\n";
    out << kSpIirCoefHighEdgeName << "=" << static_cast<int>(m.coorIIRProcess->m_coefHighEdge) << "\n";
    out << kSpIirSpeedTholdEdgeName << "=" << static_cast<int>(m.coorIIRProcess->m_speedTholdEdge) << "\n";
    out << kSpIirSpeedMaxName << "=" << m.coorIIRProcess->m_speedMax << "\n";
    out << kSpIirMaxCoefName << "=" << static_cast<int>(m.coorIIRProcess->m_maxCoef) << "\n";
    out << kSpAftCoorEnabledName << "=" << (m.aftCoorProcess->m_enabled ? "1" : "0") << "\n";
    out << kSpLockFlashInBandXName << "=" << static_cast<int>(m.aftCoorProcess->m_lockFlashInBandX) << "\n";
    out << kSpLockFlashInBandYName << "=" << static_cast<int>(m.aftCoorProcess->m_lockFlashInBandY) << "\n";
    out << kSpLockFlashEdgeXName << "=" << static_cast<int>(m.aftCoorProcess->m_lockFlashEdgeX) << "\n";
    out << kSpLockFlashEdgeYName << "=" << static_cast<int>(m.aftCoorProcess->m_lockFlashEdgeY) << "\n";
    out << kSpLockSensorTxCountName << "=" << m.aftCoorProcess->m_sensorTxCount << "\n";
    out << kSpLockSensorRxCountName << "=" << m.aftCoorProcess->m_sensorRxCount << "\n";
    out << kSpLockBypassName << "=" << (m.aftCoorProcess->m_bypassLock ? "1" : "0") << "\n";
}

// ── LoadConfig ──
void LoadConfig(StylusPipelineMembers& m, const std::string& key, const std::string& value) {
    auto toBool = [&](const std::string& v) { return ParseConfigBool(key, v); };
    try {
        if (key == kSpFrameParserEnabledName) {
            m.frameParser->m_enabled = toBool(value);
        }
        else if (key == kSpPeakDetectorEnabledName) {
            m.featureExtractor->m_enabled = toBool(value);
        }
        else if (key == kSpCoordinateSolverEnabledName) {
            m.coordinateSolver->m_enabled = toBool(value);
        }
        else if (key == kSpTiltProcessEnabledName) {
            m.tiltProcess->m_enabled = toBool(value);
            if (!m.tiltProcess->m_enabled) { m.tiltProcess->Reset(); }
        }
        else if (key == kSpPressureSolverEnabledName) {
            m.pressureSolver->m_enabled = toBool(value);
        }
        else if (key == kSpPostPressureEnabledName) {
            m.postPressure->m_enabled = toBool(value);
            if (!m.postPressure->m_enabled) { m.postPressure->Reset(); }
        }
        else if (key == kSpFakePressureDecreaseEnabledName) {
            m.postPressure->m_fakePressureDecreaseEnabled = toBool(value);
        }
        else if (key == kSpBtFreqShiftDebounceFramesName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.postPressure->m_btFreqShiftDebounceFrames = v;
        }
        else if (key == kSpPressureEdgeEnterThresholdName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 65535) v = 65535;
            m.postPressure->m_pressureEdgeEnterThreshold = static_cast<uint16_t>(v);
        }
        else if (key == kSpPressureEdgeExitThresholdName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 65535) v = 65535;
            m.postPressure->m_pressureEdgeExitThreshold = static_cast<uint16_t>(v);
        }
        else if (key == kSpTipDownPressureThresholdName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 4095) v = 4095;
            m.pressureSolver->m_tipDownPressureThreshold = static_cast<uint16_t>(v);
        }
        else if (key == kSpBtPressSignalSuppressEnterThresholdName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 65535) v = 65535;
            m.pressureSolver->m_btPressSignalSuppressEnterThreshold = static_cast<uint16_t>(v);
        }
        else if (key == kSpBtPressSignalSuppressExitThresholdName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 65535) v = 65535;
            m.pressureSolver->m_btPressSignalSuppressExitThreshold = static_cast<uint16_t>(v);
        }
        else if (key == kSpSignalFloorName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 65535) v = 65535;
            m.coordinateSolver->m_signalFloor = static_cast<uint16_t>(v);
        }
        else if (key == kSpEdgeCoorEnabledName) {
            m.edgeCoorProcess->m_enabled = toBool(value);
            if (!m.edgeCoorProcess->m_enabled) { m.edgeCoorProcess->Reset(); }
        }
        else if (key == kSpEdgeCoorPostEnabledName) {
            m.edgeCoorPostProcess->m_enabled = toBool(value);
        }
        else if (key == kSpNoisePostEnabledName) {
            m.noisePostProcess->m_enabled = toBool(value);
            if (!m.noisePostProcess->m_enabled) { m.noisePostProcess->Reset(); }
        }
        else if (key == kSpNoiseSignalRatioTholdName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 16) v = 16;
            m.noisePostProcess->m_signalRatioThreshold = static_cast<uint8_t>(v);
        }
        else if (key == kSpNoiseSignalDropRatioName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 16) v = 16;
            m.noisePostProcess->m_signalMagnitudeDropRatio = static_cast<uint8_t>(v);
        }
        else if (key == kSpLinearFilterEnabledName) {
            m.linearFilterProcess->m_enabled = toBool(value);
            if (!m.linearFilterProcess->m_enabled) { m.linearFilterProcess->Reset(); }
        }
        else if (key == kSpCoorReviseEnabledName) {
            m.coorReviseProcess->m_enabled = toBool(value);
            if (!m.coorReviseProcess->m_enabled) { m.coorReviseProcess->Reset(); }
        }
        else if (key == kSpCoorReviseFactorDim1Name) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorReviseProcess->m_factorDim1 = v;
        }
        else if (key == kSpCoorReviseFactorDim2Name) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorReviseProcess->m_factorDim2 = v;
        }
        else if (key == kSpCoorSpeedEnabledName) {
            m.coorSpeedProcess->m_enabled = toBool(value);
            if (!m.coorSpeedProcess->m_enabled) { m.coorSpeedProcess->Reset(); }
        }
        else if (key == kSpIirFilterEnabledName) {
            m.coorIIRProcess->m_enabled = toBool(value);
            if (!m.coorIIRProcess->m_enabled) { m.coorIIRProcess->Reset(); }
        }
        else if (key == kSpIirCoefLowInBandName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorIIRProcess->m_coefLowInBand = static_cast<uint8_t>(v);
        }
        else if (key == kSpIirCoefHighInBandName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorIIRProcess->m_coefHighInBand = static_cast<uint8_t>(v);
        }
        else if (key == kSpIirSpeedTholdInBandName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorIIRProcess->m_speedTholdInBand = static_cast<uint8_t>(v);
        }
        else if (key == kSpIirCoefLowEdgeName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorIIRProcess->m_coefLowEdge = static_cast<uint8_t>(v);
        }
        else if (key == kSpIirCoefHighEdgeName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorIIRProcess->m_coefHighEdge = static_cast<uint8_t>(v);
        }
        else if (key == kSpIirSpeedTholdEdgeName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorIIRProcess->m_speedTholdEdge = static_cast<uint8_t>(v);
        }
        else if (key == kSpIirSpeedMaxName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 1000) v = 1000;
            m.coorIIRProcess->m_speedMax = v;
        }
        else if (key == kSpIirMaxCoefName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.coorIIRProcess->m_maxCoef = static_cast<uint8_t>(v);
        }
        else if (key == kSpAftCoorEnabledName) {
            m.aftCoorProcess->m_enabled = toBool(value);
            if (!m.aftCoorProcess->m_enabled) { m.aftCoorProcess->Reset(); }
        }
        else if (key == kSpLockFlashInBandXName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.aftCoorProcess->m_lockFlashInBandX = static_cast<uint8_t>(v);
        }
        else if (key == kSpLockFlashInBandYName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.aftCoorProcess->m_lockFlashInBandY = static_cast<uint8_t>(v);
        }
        else if (key == kSpLockFlashEdgeXName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.aftCoorProcess->m_lockFlashEdgeX = static_cast<uint8_t>(v);
        }
        else if (key == kSpLockFlashEdgeYName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 255) v = 255;
            m.aftCoorProcess->m_lockFlashEdgeY = static_cast<uint8_t>(v);
        }
        else if (key == kSpLockSensorTxCountName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 200) v = 200;
            m.aftCoorProcess->m_sensorTxCount = v;
        }
        else if (key == kSpLockSensorRxCountName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 200) v = 200;
            m.aftCoorProcess->m_sensorRxCount = v;
        }
        else if (key == kSpLockBypassName) {
            m.aftCoorProcess->m_bypassLock = toBool(value);
        }
    } catch (const ConfigParseError& error) {
        LogConfigParseWarning("StylusPipeline", __func__, key, value, error);
    }
}

}  // namespace StylusConfig
}  // namespace Solvers

#endif  // EGOTOUCH_CONFIG_ENABLED
