// Auto-generated by scripts/config_key_sync.py — DO NOT EDIT
// Source: config/stylus_pipeline_config.yaml

#pragma once

#include <cstdint>
#include <iosfwd>
#include <string>
#include <vector>

#include "SolverBuildConfig.h"

namespace Solvers {
struct ConfigParam;
namespace Stylus {
class StylusFrameParser;
class GridFeatureExtractor;
class CoordinateSolver;
class TiltProcess;
class PressureSolver;
class Hpp3PostPressureProcess;
class EdgeCoorProcess;
class EdgeCoorPostProcess;
class Hpp3NoisePostProcess;
class LinearFilterProcess;
class CoorReviseProcess;
class CoorSpeedProcess;
class CoorIIRProcess;
class AftCoorProcess;
} // namespace Stylus

namespace StylusConfig {

// ── Active config key defaults (shared by Debug/Release) ──
constexpr bool kSpFrameParserEnabled = true;
constexpr bool kSpPeakDetectorEnabled = true;
constexpr bool kSpCoordinateSolverEnabled = true;
constexpr bool kSpTiltProcessEnabled = true;
constexpr bool kSpPressureSolverEnabled = true;
constexpr bool kSpPostPressureEnabled = true;
constexpr bool kSpFakePressureDecreaseEnabled = false;
constexpr int kSpBtFreqShiftDebounceFrames = 2;
constexpr uint16_t kSpPressureEdgeEnterThreshold = 1500;
constexpr uint16_t kSpPressureEdgeExitThreshold = 3000;
constexpr uint16_t kSpTipDownPressureThreshold = 1;
constexpr uint16_t kSpBtPressSignalSuppressEnterThreshold = 2200;
constexpr uint16_t kSpBtPressSignalSuppressExitThreshold = 3200;
constexpr uint16_t kSpSignalFloor = 64;
constexpr bool kSpEdgeCoorEnabled = true;
constexpr bool kSpEdgeCoorPostEnabled = true;
constexpr bool kSpNoisePostEnabled = true;
constexpr uint8_t kSpNoiseSignalRatioThold = 5;
constexpr uint8_t kSpNoiseSignalDropRatio = 5;
constexpr bool kSpLinearFilterEnabled = true;
constexpr bool kSpCoorReviseEnabled = true;
constexpr int kSpCoorReviseFactorDim1 = 5;
constexpr int kSpCoorReviseFactorDim2 = 5;
constexpr bool kSpCoorSpeedEnabled = true;
constexpr bool kSpIirFilterEnabled = true;
constexpr uint8_t kSpIirCoefLowInBand = 2;
constexpr uint8_t kSpIirCoefHighInBand = 16;
constexpr uint8_t kSpIirSpeedTholdInBand = 20;
constexpr uint8_t kSpIirCoefLowEdge = 6;
constexpr uint8_t kSpIirCoefHighEdge = 18;
constexpr uint8_t kSpIirSpeedTholdEdge = 10;
constexpr int kSpIirSpeedMax = 205;
constexpr uint8_t kSpIirMaxCoef = 32;
constexpr bool kSpAftCoorEnabled = true;
constexpr uint8_t kSpLockFlashInBandX = 0;
constexpr uint8_t kSpLockFlashInBandY = 0;
constexpr uint8_t kSpLockFlashEdgeX = 1;
constexpr uint8_t kSpLockFlashEdgeY = 2;
constexpr int kSpLockSensorTxCount = 60;
constexpr int kSpLockSensorRxCount = 40;
constexpr bool kSpLockBypass = false;

// ── Active key name constants ──
constexpr const char* kSpFrameParserEnabledName = "sp.frameParserEnabled";
constexpr const char* kSpPeakDetectorEnabledName = "sp.peakDetectorEnabled";
constexpr const char* kSpCoordinateSolverEnabledName = "sp.coordinateSolverEnabled";
constexpr const char* kSpTiltProcessEnabledName = "sp.tiltProcessEnabled";
constexpr const char* kSpPressureSolverEnabledName = "sp.pressureSolverEnabled";
constexpr const char* kSpPostPressureEnabledName = "sp.postPressureEnabled";
constexpr const char* kSpFakePressureDecreaseEnabledName = "sp.fakePressureDecreaseEnabled";
constexpr const char* kSpBtFreqShiftDebounceFramesName = "sp.btFreqShiftDebounceFrames";
constexpr const char* kSpPressureEdgeEnterThresholdName = "sp.pressureEdgeEnterThreshold";
constexpr const char* kSpPressureEdgeExitThresholdName = "sp.pressureEdgeExitThreshold";
constexpr const char* kSpTipDownPressureThresholdName = "sp.tipDownPressureThreshold";
constexpr const char* kSpBtPressSignalSuppressEnterThresholdName = "sp.btPressSignalSuppressEnterThreshold";
constexpr const char* kSpBtPressSignalSuppressExitThresholdName = "sp.btPressSignalSuppressExitThreshold";
constexpr const char* kSpSignalFloorName = "sp.signalFloor";
constexpr const char* kSpEdgeCoorEnabledName = "sp.edgeCoorEnabled";
constexpr const char* kSpEdgeCoorPostEnabledName = "sp.edgeCoorPostEnabled";
constexpr const char* kSpNoisePostEnabledName = "sp.noisePostEnabled";
constexpr const char* kSpNoiseSignalRatioTholdName = "sp.noiseSignalRatioThold";
constexpr const char* kSpNoiseSignalDropRatioName = "sp.noiseSignalDropRatio";
constexpr const char* kSpLinearFilterEnabledName = "sp.linearFilterEnabled";
constexpr const char* kSpCoorReviseEnabledName = "sp.coorReviseEnabled";
constexpr const char* kSpCoorReviseFactorDim1Name = "sp.coorReviseFactorDim1";
constexpr const char* kSpCoorReviseFactorDim2Name = "sp.coorReviseFactorDim2";
constexpr const char* kSpCoorSpeedEnabledName = "sp.coorSpeedEnabled";
constexpr const char* kSpIirFilterEnabledName = "sp.iirFilterEnabled";
constexpr const char* kSpIirCoefLowInBandName = "sp.iirCoefLowInBand";
constexpr const char* kSpIirCoefHighInBandName = "sp.iirCoefHighInBand";
constexpr const char* kSpIirSpeedTholdInBandName = "sp.iirSpeedTholdInBand";
constexpr const char* kSpIirCoefLowEdgeName = "sp.iirCoefLowEdge";
constexpr const char* kSpIirCoefHighEdgeName = "sp.iirCoefHighEdge";
constexpr const char* kSpIirSpeedTholdEdgeName = "sp.iirSpeedTholdEdge";
constexpr const char* kSpIirSpeedMaxName = "sp.iirSpeedMax";
constexpr const char* kSpIirMaxCoefName = "sp.iirMaxCoef";
constexpr const char* kSpAftCoorEnabledName = "sp.aftCoorEnabled";
constexpr const char* kSpLockFlashInBandXName = "sp.lockFlashInBandX";
constexpr const char* kSpLockFlashInBandYName = "sp.lockFlashInBandY";
constexpr const char* kSpLockFlashEdgeXName = "sp.lockFlashEdgeX";
constexpr const char* kSpLockFlashEdgeYName = "sp.lockFlashEdgeY";
constexpr const char* kSpLockSensorTxCountName = "sp.lockSensorTxCount";
constexpr const char* kSpLockSensorRxCountName = "sp.lockSensorRxCount";
constexpr const char* kSpLockBypassName = "sp.lockBypass";

#if EGOTOUCH_CONFIG_ENABLED

struct StylusPipelineMembers {
    Stylus::StylusFrameParser* frameParser;
    Stylus::GridFeatureExtractor* featureExtractor;
    Stylus::CoordinateSolver* coordinateSolver;
    Stylus::TiltProcess* tiltProcess;
    Stylus::PressureSolver* pressureSolver;
    Stylus::Hpp3PostPressureProcess* postPressure;
    Stylus::EdgeCoorProcess* edgeCoorProcess;
    Stylus::EdgeCoorPostProcess* edgeCoorPostProcess;
    Stylus::Hpp3NoisePostProcess* noisePostProcess;
    Stylus::LinearFilterProcess* linearFilterProcess;
    Stylus::CoorReviseProcess* coorReviseProcess;
    Stylus::CoorSpeedProcess* coorSpeedProcess;
    Stylus::CoorIIRProcess* coorIIRProcess;
    Stylus::AftCoorProcess* aftCoorProcess;
};

void LoadConfig(StylusPipelineMembers& m, const std::string& key, const std::string& value);
void SaveConfig(const StylusPipelineMembers& m, std::ostream& out);
std::vector<ConfigParam> GetConfigSchema(StylusPipelineMembers& m);

#endif  // EGOTOUCH_CONFIG_ENABLED

}  // namespace StylusConfig
}  // namespace Solvers
