#pragma once

#include <cstdint>

namespace Config {

// ConfigKeyId: 紧凑的 16-bit 配置键 ID。
// 布局: high byte = 模块分区, low byte = 模块内序号
//
//   Service:    0x00xx
//   Touch:      0x01xx
//   Stylus:     0x02xx
//   Reserved:   0x03xx

enum class ConfigKeyId : uint16_t {
    // ── Service (0x0000-0x00FF) ──
    SvcMode              = 0x0000,
    SvcAutoMode          = 0x0001,
    SvcStylusVhfEnabled  = 0x0002,
    SvcPenButtonMode     = 0x0003,
    SvcPenButtonRoute    = 0x0004,

    // ── Touch (0x0100-0x01FF) ──
    TouchBaselineBgAlphaShift     = 0x0100,
    TouchBaselineBgMaxStep        = 0x0101,
    TouchBaselineNoFingerAlphaShift = 0x0102,
    TouchBaselineNoFingerMaxStep  = 0x0103,
    TouchBaselineRecoveryAlphaShift = 0x0104,
    TouchBaselineRecoveryMaxFrames  = 0x0105,
    TouchBaselineRecoveryMaxStep  = 0x0106,
    TouchFrameParserEnabled       = 0x0107,
    TouchBaselineEnabled          = 0x0108,
    TouchBaselineValue            = 0x0109,
    TouchBaselineNoiseDeadband    = 0x010A,
    TouchBaselinePositiveDeadband = 0x010B,
    TouchBaselineNegativeDeadband = 0x010C,
    TouchBaselinePeakThreshold    = 0x010D,
    TouchBaselineReleaseHoldFrames = 0x010E,
    TouchBaselinePositiveAlphaShift = 0x010F,
    TouchBaselineNegativeAlphaShift = 0x0110,
    TouchBaselineNoiseAlphaShift  = 0x0111,
    TouchBaselinePositiveMaxStep  = 0x0112,
    TouchBaselineNegativeMaxStep  = 0x0113,
    TouchBaselineNoiseTrackingEnabled = 0x0114,
    TouchCmfEnabled               = 0x0115,
    TouchCmfExclusionThreshold    = 0x0116,
    TouchCmfMaxCorrection         = 0x0117,
    TouchPeakDetectionThreshold   = 0x0118,
    TouchPeakDetectionMaxPeaks    = 0x0119,
    TouchPeakDetectionLocalMaxRadius = 0x011A,
    TouchPeakDetectionEdgeThresholdEnabled = 0x011B,
    TouchPeakDetectionEdgeThreshold = 0x011C,
    TouchPeakDetectionZ8FilterEnabled = 0x011D,
    TouchPeakDetectionZ1FilterEnabled = 0x011E,
    TouchPeakDetectionClosePeakSaddleFilterEnabled = 0x011F,
    TouchPeakDetectionClosePeakRadius = 0x0120,
    TouchPeakDetectionMacroZoneMinArea = 0x0121,
    TouchClassifierEnabled        = 0x0122,
    TouchClassifierAnalyzerEnabled = 0x0123,
    TouchClassifierPeakEvalEnabled = 0x0124,
    TouchClassifierAreaThreshold  = 0x0125,
    TouchClassifierSignalSumThreshold = 0x0126,
    TouchClassifierFingerProminence = 0x0127,
    TouchClassifierFingerSharpness = 0x0128,
    TouchClassifierPalmSharpnessMax = 0x0129,
    TouchClassifierPalmAwareExpansionEnabled = 0x012A,
    TouchClassifierFingerInPalmThresholdRatio = 0x012B,
    TouchClassifierFingerInPalmMaxRadius = 0x012C,
    TouchZoneContactThresholdScaleNumer = 0x012D,
    TouchZoneContactThresholdScaleShift = 0x012E,
    TouchZoneContactDilateErodeEnabled = 0x012F,
    TouchZoneContactMaxTouches    = 0x0130,
    TouchZoneContactEdgeWidthThreshold = 0x0131,
    TouchZoneContactTouchSizePixelPitchMm = 0x0132,
    TouchZoneContactTouchSizeUnitPerSigMm2 = 0x0133,
    TouchEdgeEnabled              = 0x0134,
    TouchEdgeCompStrength         = 0x0135,
    TouchEdgeFullCompRange        = 0x0136,
    TouchEdgeBlendRange           = 0x0137,
    TouchEdgeRejectEnabled        = 0x0138,
    TouchEdgeRejectMargin         = 0x0139,
    TouchTrackingEnabled          = 0x013A,
    TouchTrackingMaxTouchCount    = 0x013B,
    TouchTrackingMaxTrackDistance = 0x013C,
    TouchTrackingAlwaysMatchDistance = 0x013D,
    TouchTrackingGapRelinkEnabled = 0x013E,
    TouchTrackingGapRelinkWindowFrames = 0x013F,
    TouchTrackingTouchDownDebounceFrames = 0x0140,
    TouchTrackingDynamicDebounceEnabled = 0x0141,
    TouchTrackingUseHungarian     = 0x0142,
    TouchStylusSuppressGlobalEnabled = 0x0143,
    TouchStylusSuppressLocalEnabled = 0x0144,
    TouchStylusSuppressLocalDistance = 0x0145,
    TouchStylusSuppressPenPeakThreshold = 0x0146,
    TouchStylusSuppressAftEnabled = 0x0147,
    TouchStylusSuppressAftRecentFrames = 0x0148,
    TouchStylusSuppressAftRadius  = 0x0149,
    TouchCoordFilterEnabled       = 0x014A,
    TouchCoordFilterMinCutoff     = 0x014B,
    TouchCoordFilterBeta          = 0x014C,
    TouchCoordFilterDCutoff       = 0x014D,
    TouchGestureEnabled           = 0x014E,
    TouchGesturePressCandidateFrames = 0x014F,
    TouchGestureDragThreshold     = 0x0150,
    TouchGestureLongPressFrames   = 0x0151,
    TouchGestureReleasePendingFrames = 0x0152,
    TouchGestureBypassStateMachine = 0x0153,
    TouchPalmBoxEnabled           = 0x0154,
    TouchPalmBoxExpandRows        = 0x0155,
    TouchPalmBoxExpandCols        = 0x0156,
    TouchPalmBoxMatchCenterDistance = 0x0157,
    TouchPalmBoxMatchIouThreshold = 0x0158,
    TouchPalmBoxPalmLikelyOnly    = 0x0159,
    TouchPalmBoxKeepUntilNoPeakDomainInside = 0x015A,
    TouchPalmBoxMaxHoldFrames     = 0x015B,

    // ── Stylus: reserved legacy HPP2 config key range (0x0200-0x022F) ──

    // ── Stylus: SP (0x0230-0x027F) ──
    StylusSpFrameParserEnabled            = 0x0230,
    StylusSpPeakDetectorEnabled           = 0x0231,
    StylusSpCoordinateSolverEnabled       = 0x0232,
    StylusSpTiltProcessEnabled            = 0x0233,
    StylusSpPressureSolverEnabled         = 0x0234,
    StylusSpPostPressureEnabled           = 0x0235,
    StylusSpFakePressureDecreaseEnabled   = 0x0236,
    StylusSpBtFreqShiftDebounceFrames     = 0x0237,
    StylusSpPressureEdgeEnterThreshold    = 0x0238,
    StylusSpPressureEdgeExitThreshold     = 0x0239,
    StylusSpTipDownPressureThreshold      = 0x023A,
    StylusSpBtPressSuppressEnterThreshold = 0x023B,
    StylusSpBtPressSuppressExitThreshold  = 0x023C,
    StylusSpSignalFloor                   = 0x023D,
    StylusSpEdgeCoorEnabled               = 0x023E,
    StylusSpEdgeCoorPostEnabled           = 0x023F,
    StylusSpNoisePostEnabled              = 0x0240,
    StylusSpNoiseSignalRatioThold         = 0x0241,
    StylusSpNoiseSignalDropRatio          = 0x0242,
    StylusSpLinearFilterEnabled           = 0x0243,
    StylusSpCoorReviseEnabled             = 0x0244,
    StylusSpCoorReviseFactorDim1          = 0x0245,
    StylusSpCoorReviseFactorDim2          = 0x0246,
    StylusSpCoorSpeedEnabled              = 0x0247,
    StylusSpIirFilterEnabled              = 0x0248,
    // Historical TLV IDs retained; names corrected from InBand/Edge to Hover/Writing.
    StylusSpIirCoefLowHover               = 0x0249,
    StylusSpIirCoefHighHover              = 0x024A,
    StylusSpIirSpeedTholdHover            = 0x024B,
    StylusSpIirCoefLowWriting             = 0x024C,
    StylusSpIirCoefHighWriting            = 0x024D,
    StylusSpIirSpeedTholdWriting          = 0x024E,
    StylusSpIirSpeedMax                   = 0x024F,
    StylusSpIirMaxCoef                    = 0x0250,
    StylusSpAftCoorEnabled                = 0x0251,
    StylusSpLockFlashInBandX              = 0x0252,
    StylusSpLockFlashInBandY              = 0x0253,
    StylusSpLockFlashEdgeX                = 0x0254,
    StylusSpLockFlashEdgeY                = 0x0255,
    StylusSpLockSensorTxCount             = 0x0256,
    StylusSpLockSensorRxCount             = 0x0257,
    StylusSpLockBypass                    = 0x0258,

    // ── Sentinel ──
    MaxKeyId = 0x0300,
};

} // namespace Config
