// Auto-generated by scripts/config_key_sync.py — DO NOT EDIT
// Source: config/touch_pipeline_config.yaml

#pragma once

#include <cstdint>
#include <iosfwd>
#include <string>
#include <vector>

#include "SolverBuildConfig.h"

namespace Solvers {
struct ConfigParam;
namespace Touch {
class MasterFrameParser;
class BaselineTracker;
class CMFProcessor;
class MacroZoneDetector;
class PeakDetector;
class TouchClassifier;
class ContactExtractor;
class EdgeCompensator;
class EdgeRejector;
class StylusTouchSuppressor;
class TouchTracker;
class CoordinateFilter;
class TouchGestureStateMachine;
} // namespace Touch

namespace TouchConfig {

// ── Active config key defaults (shared by Debug/Release) ──
constexpr int kBaselineBackgroundAlphaShift = 3;
constexpr int kBaselineBackgroundMaxStep = 512;
constexpr int kBaselineNoFingerAlphaShift = 3;
constexpr int kBaselineNoFingerMaxStep = 512;
constexpr int kBaselineRecoveryAlphaShift = 2;
constexpr int kBaselineRecoveryMaxFrames = 30;
constexpr int kBaselineRecoveryMaxStep = 256;

// ── Active key name constants ──
constexpr const char* kBaselineBackgroundAlphaShiftName = "BaselineBackgroundAlphaShift";
constexpr const char* kBaselineBackgroundMaxStepName = "BaselineBackgroundMaxStep";
constexpr const char* kBaselineNoFingerAlphaShiftName = "BaselineNoFingerAlphaShift";
constexpr const char* kBaselineNoFingerMaxStepName = "BaselineNoFingerMaxStep";
constexpr const char* kBaselineRecoveryAlphaShiftName = "BaselineRecoveryAlphaShift";
constexpr const char* kBaselineRecoveryMaxFramesName = "BaselineRecoveryMaxFrames";
constexpr const char* kBaselineRecoveryMaxStepName = "BaselineRecoveryMaxStep";

#if EGOTOUCH_CONFIG_ENABLED

struct TouchPipelineMembers {
    Touch::MasterFrameParser* frameParser;
    Touch::BaselineTracker* baseline;
    Touch::CMFProcessor* cmf;
    Touch::MacroZoneDetector* macroZoneDet;
    Touch::PeakDetector* peakDet;
    Touch::TouchClassifier* touchClassifier;
    Touch::ContactExtractor* contactExtractor;
    Touch::EdgeCompensator* edgeComp;
    Touch::EdgeRejector* edgeReject;
    Touch::StylusTouchSuppressor* stylusSuppress;
    Touch::TouchTracker* tracker;
    Touch::CoordinateFilter* coordFilter;
    Touch::TouchGestureStateMachine* gesture;
};

void LoadConfig(TouchPipelineMembers& m, const std::string& key, const std::string& value);
void SaveConfig(const TouchPipelineMembers& m, std::ostream& out);
std::vector<ConfigParam> GetConfigSchema(TouchPipelineMembers& m);

#endif  // EGOTOUCH_CONFIG_ENABLED

}  // namespace TouchConfig
}  // namespace Solvers
